### ISSUE TITLE
Wallpaper issues

### ISSUE THREAD

**Issue by Naboa** [NoteConnect/Releases#1]
Hello
I was really exited to tryed the software, it's look exactly what I'm looking for :) 
The thing is, i'm stuck on the first step to create a note. The wallpaper won't show up and I  can't go ahead. 
Here a screenshot of my issues 
![image](https://user-images.githubusercontent.com/114988505/194097081-581d44e1-160d-4620-b5ca-5bf0089a7a6b.png)

I got windows 10 x64
Thanks !

**Comment by ZeroX-DG** [comment]
Hi! Thanks for trying out the app. Unfortunately I've discontinued the app because there are other apps that can do what my app does. You should check out:
- https://obsidian.md/
- https://milanote.com/
